name: Deploy to Aliyun

on:
  push:
    branches:
      - master  # 当 push 到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 连接到阿里云服务器并执行部署脚本
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            bash /var/www/deploy.sh
